---
include:
  - board: seeeduino_xiao_ble
    shield: scylla prospector_adapter scylla_dongle
    # cmake-args: "" # We might re-evaluate if cmake-args are needed later
  - board: nrfmicro_13
    shield: scylla_left
  - board: nrfmicro_13
    shield: scylla_right
