---
include:
  - board: seeeduino_xiao_ble
    shield: scylla prospector_adapter scylla_dongle
    cmake-args: ""
  - board: nrfmicro_13
    shield: scylla_left
  - board: nrfmicro_13
    shield: scylla_right
