---
include:
  - board: seeeduino_xiao_ble
    shield: scylla_dongle prospector_adapter
  - board: nrfmicro_13
    shield: scylla_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: nrfmicro_13
    shield: scylla_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n


