manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: infused-kim
      url-base: https://github.com/infused-kim
    - name: carrefinho
      url-base: https://github.com/carrefinho
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main # Or a specific tag like '3.5' for stability
      import: app/west.yml
    - name: prospector-zmk-module
      remote: carrefinho
      revision: main
  self:
    path: config
